name: Deploy to VPS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute deployment commands on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          script: |
            cd CodingWorkspace/Projects/signal-x
            
            git checkout deploy
            git fetch --all
            git reset --hard origin/deploy
            rm -rf frontend/.next
            rm -rf backend/.next
            
            docker compose up -d --build
            
            docker image prune -f